package com.myspace.changerequest_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Helpdesk implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Đơn vị yêu cầu")
	private java.lang.String donviyeucau;
	@org.kie.api.definition.type.Label(value = "Khách hàng")
	private java.lang.String khachhang;
	@org.kie.api.definition.type.Label(value = "Mã CR")
	private java.lang.String maCr;
	@org.kie.api.definition.type.Label(value = "Mô tả sơ bộ")
	private java.lang.String mota;
	@org.kie.api.definition.type.Label(value = "Ngày yêu cầu")
	private java.util.Date ngayyeucau;
	@org.kie.api.definition.type.Label(value = "Người yêu cầu")
	private java.lang.String nguoiyeucau;
	@org.kie.api.definition.type.Label(value = "Tên CR")
	private java.lang.String tenCr;
	@org.kie.api.definition.type.Label(value = "Ghi chú")
	private java.lang.String ghichu;
	@org.kie.api.definition.type.Label(value = "Nội dung yêu cầu thay đổi")
	private java.lang.String noidung;
	@org.kie.api.definition.type.Label(value = "Quy trình xử lý hiện tại")
	private java.lang.String quytrinh;
	@org.kie.api.definition.type.Label(value = "Thời gian yêu cầu hoàn thành")
	private java.util.Date thoigian;

	public Helpdesk() {
	}

	public java.lang.String getDonviyeucau() {
		return this.donviyeucau;
	}

	public void setDonviyeucau(java.lang.String donviyeucau) {
		this.donviyeucau = donviyeucau;
	}

	public java.lang.String getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(java.lang.String khachhang) {
		this.khachhang = khachhang;
	}

	public java.lang.String getMaCr() {
		return this.maCr;
	}

	public void setMaCr(java.lang.String maCr) {
		this.maCr = maCr;
	}

	public java.lang.String getMota() {
		return this.mota;
	}

	public void setMota(java.lang.String mota) {
		this.mota = mota;
	}

	public java.util.Date getNgayyeucau() {
		return this.ngayyeucau;
	}

	public void setNgayyeucau(java.util.Date ngayyeucau) {
		this.ngayyeucau = ngayyeucau;
	}

	public java.lang.String getNguoiyeucau() {
		return this.nguoiyeucau;
	}

	public void setNguoiyeucau(java.lang.String nguoiyeucau) {
		this.nguoiyeucau = nguoiyeucau;
	}

	public java.lang.String getTenCr() {
		return this.tenCr;
	}

	public void setTenCr(java.lang.String tenCr) {
		this.tenCr = tenCr;
	}

	public java.lang.String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(java.lang.String ghichu) {
		this.ghichu = ghichu;
	}

	public java.lang.String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(java.lang.String noidung) {
		this.noidung = noidung;
	}

	public java.lang.String getQuytrinh() {
		return this.quytrinh;
	}

	public void setQuytrinh(java.lang.String quytrinh) {
		this.quytrinh = quytrinh;
	}

	public java.util.Date getThoigian() {
		return this.thoigian;
	}

	public void setThoigian(java.util.Date thoigian) {
		this.thoigian = thoigian;
	}

	public Helpdesk(java.lang.String donviyeucau, java.lang.String khachhang,
			java.lang.String maCr, java.lang.String mota,
			java.util.Date ngayyeucau, java.lang.String nguoiyeucau,
			java.lang.String tenCr, java.lang.String ghichu,
			java.lang.String noidung, java.lang.String quytrinh,
			java.util.Date thoigian) {
		this.donviyeucau = donviyeucau;
		this.khachhang = khachhang;
		this.maCr = maCr;
		this.mota = mota;
		this.ngayyeucau = ngayyeucau;
		this.nguoiyeucau = nguoiyeucau;
		this.tenCr = tenCr;
		this.ghichu = ghichu;
		this.noidung = noidung;
		this.quytrinh = quytrinh;
		this.thoigian = thoigian;
	}

}